### ISSUE TITLE
UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names   warnings.warn(

### ISSUE THREAD

**Issue by janceviciusjulius** [danielm09/rf_youtube#2]
Good morning, Daniel

Firstly, I would like to say, that your script is amazing, and thank You for your answer yesterday on YouTube. I would like to ask for some answers to my question and I hope You will find time to answer them. 

1. Then I run the script I always get this warning. Maybe I did something wrong?
**Warning:** UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names warnings.warn(.

2. In your script line (df = pd.read_csv(r'...\CHECK RANDOM FOREST\training_data.csv', sep=';')) separator is ";", but in my script I cannot run it, when I change ir to "," everything works fine. Is that okey? **My training file:**
![image](https://user-images.githubusercontent.com/64422065/153355888-8da5f2ed-91e9-49fb-84ca-68c00009f481.png)

3. I am getting this error: numpy.core._exceptions.MemoryError: Unable to allocate 2.69 GiB for an array with shape (120560400, 1, 3) and data type float64
![image](https://user-images.githubusercontent.com/64422065/153355965-0e457a06-e59c-4ae0-970d-e928230d6969.png)

Maybe this is a reason for the previous question? To my mind, it is not. You wrote yesterday, that maybe changing the data type would help. I used QGIS to check my .tiff file data type and if I am correct it is - UInt16 - Sixteen-bit unsigned integer.
![image](https://user-images.githubusercontent.com/64422065/153356310-9b6e8a23-75e8-4f6a-a27f-8e3f45c03671.png)

Or it is a big picture fault because X: 10980 Y: 10980 Bands: 3?

I hope to get an answer from You! Thank You for your time! Looking forward to hearing from You.

**Comment by janceviciusjulius** [comment]
In addition, I would to add an error, which I got the first time:
4. 
![image](https://user-images.githubusercontent.com/64422065/153364765-054d77aa-6c8f-4f0e-b89c-0ce9e7f81fd2.png)

**Comment by danielm09** [comment]
Hi. I will try to answer to your questions.

1. I looked up online and it seems that you get this error if you're passing a dataframe in the fit function. Instead, you want to pass a list or series (that is, you want to pass a single column of the dataframe). If you see in the original code, I define the variable `label` as `label = df['COD']`. This means that `label` values come from a column in the `df` dataframe.

2. Yes, it is okay. You want to use the separator that is on your csv file. I used `;` but the default is `,`.

3. As I said on my reply on youtube, it means that you do not have enough memory. I suggested some strategies on the reply. But considering that your tif is Uint16, you definetly can save some memory, since Python is reading as float64. You could try using `array = ds.ReadAsArray().astype('uint16')`. I'm not sure if this is going to work though, because maybe Python needs to store the array as float64 first (thus giving a memory error) to convert to uint16 after.
If it keeps giving you memory error, you could go to QGIS and split you image in 2 (or 3, 4... whatever fits in your memory) and then performing 2 (3, 4...) classifications, one for each split.
One last alternative would be reading the image in chunks. That's a little bit more complicated, but it is definetly doable. Check this post to get some insights [https://gis.stackexchange.com/questions/233764/reading-an-image-as-array-in-python-using-gdal](url)

I hope this helps.

**Comment by janceviciusjulius** [comment]
Thank You for your answer and time.

Final question: As I understood, there is no way to hide or fix that warning? (Talking about first previous question)

**Comment by danielm09** [comment]
It seems that there is this new feature on the RandomForestClassifier called feature_names_in_, and there could be some sort of bug going on.

From what I read online, it seems that using the method `values` might remove the warning.
So you could try to replace the fit part for this one: `clf.fit(data.values, label.values)`

Hope this helps.

**Comment by janceviciusjulius** [comment]
Thank You!

**Comment by janceviciusjulius** [comment]
I am so sorry to ask again, but on one computer - everything is fine, while on another I got this mistake, tried to reinstall, update, but nothing worked. Maybe You have experience with this one and know how to solve it? 
![image](https://user-images.githubusercontent.com/64422065/153553995-ce963f79-e152-4c24-b4c0-c59210e26144.png)

Thank You very much!

**Comment by janceviciusjulius** [comment]
Hello, I am sorry for asking You, but I have one more question. It is about training data. In your video, I can see that there are a lot of lines in .csv file. How do you get that? Have you written the special script, or used QGIS, put some dots and etc. Maybe you can explain a little bit more, how you get that?

**Comment by danielm09** [comment]
I manually placed points on QGIS and then used the "Sample raster values" tool to get the band values into the points.

**Comment by janceviciusjulius** [comment]
Thank You, I found "Simple raster value" tool. Maybe You have heard, it is possible to save raster values and coordinates at the same time?

**Comment by danielm09** [comment]
I'm sure you can do this in QGIS. A quick google would give you some directions.

**Comment by janceviciusjulius** [comment]
I could not find that. I will try once more. Thank You!
