### ISSUE TITLE
Colourful output file

### ISSUE THREAD

**Issue by janceviciusjulius** [danielm09/rf_youtube#3]
Good afternoon,

I have one simple question: what is the difference between using INT32 or INT16 while creating a .tiff file in your script? It is connected with accuracy? If yes, maybe you have spotted how much?

**Comment by danielm09** [comment]
Hi.

You want to use INT32 when you have a value that is greater than the INT16 max value (32767). For instance, if your classification has a class whose code is 91000, you cannot use INT16 in this case, as 91000 is greater than 32767.
Instead, you use INT32, which has a much larger max value, thus allowing you to represent the 91000 class.

**Comment by janceviciusjulius** [comment]
Thank You for your answer. Now I understood. 

Maybe you know, how we can give label names?
![image](https://user-images.githubusercontent.com/64422065/158391438-c11a5516-3d4a-4cbb-ba15-fc3c62826e95.png)

For instance, a class whose value is 1 (blue colour) has label 1. It is possible to set it to "Water" in python code?

**Comment by danielm09** [comment]
If you're asking if you could create a raster with strings instead of numbers, the answer is no.

But if you're using QGIS and you have a fixed class structure, you can create a colormap file with the class code, class label and class color. Check this [link](https://gis.stackexchange.com/questions/388300/symbology-in-qgis-raster-with-complex-discrete-data)

I think it should be pretty easy to create the colormap file automatically in python, just follow the file structure.

**Comment by janceviciusjulius** [comment]
Thank You, apologies for interrupting you once again. Have a nice day!
